blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("post/<int:pk>/", views.blog_detail, name="blog_detail"),
    path("category/<category>/", views.blog_category, name="blog_category"),
    path("search/", views.blog_search, name="blog_search"),
    path("advanced_search/", views.advanced_search, name="advanced_search"),
    path("archive/<int:year>/<int:month>/<int:day>/", views.ArchiveDayView.as_view(), name="archive_day"),
    path("archive/<int:year>/<int:month>/", views.ArchiveMonthView.as_view(), name="archive_month"),
    path("archive/<int:year>/", views.ArchiveYearView.as_view(), name="archive_year"),
    path("archives/", views.ArchiveView.as_view(), name="blog_archives"),
]

personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include

# import for static files in dev
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# import for media files in dev
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path('markdownx/', include("markdownx.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name="categories")
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    created_on = models.DateTimeField(default=now)
    last_modified = models.DateTimeField(auto_now=True)
    body = MarkdownxField()
    categories = models.ManyToManyField("Category", through="Connection", related_name="posts")

    # Create a property that returns the markdown instead
    @property
    def formatted_markdown(self):
        return markdownify(self.body)

    def __str__(self):
        return self.title


class Connection(models.Model):
    category = models.ForeignKey("Category", verbose_name="category", on_delete=models.CASCADE)
    post = models.ForeignKey("Post", verbose_name="post", on_delete=models.CASCADE)
    comment = models.TextField(blank=True)

blog/views.py
from .calendar import HTMLCalendar
from .filters import PostFilter
from .models import *
from datetime import date
from django.contrib.postgres.search import SearchVector, SearchQuery
from django.core.paginator import Paginator
from django.db.models.functions import TruncMonth
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import TemplateView



paginate_count = 5  # This is basically a global variable.
def paginate(queryset, request):
    paginator = Paginator(queryset, paginate_count)
    page_number = request.GET.get("page")
    return paginator.get_page(page_number)



def blog_index(request):
    posts = Post.objects.all().order_by("-created_on")

    # Output to Template
    context = {
        "page_obj": paginate(posts, request),
    }
    return render(request, "blog/index.html", context)



def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name = category
        ).order_by("-created_on")

    # Output to Template
    category = Category.objects.get(name=category)
    category_edit_url = reverse("admin:{}_{}_change"
                  .format(category._meta.app_label, category._meta.model_name), 
                  args=[category.id])
    page_title = 'category: <a href="{}">{}</a>'.format(category_edit_url, category)

    context = {
        "site_title": 'Category: {}'.format(category),
        "page_title": page_title,
        "category": category,
        "page_obj": paginate(posts, request),
    }
    return render(request, "blog/category.html", context)



def blog_detail(request, pk):
    try:
        post = Post.objects.get(pk=pk)

        # Output to Template
        post_edit_url = reverse("admin:{}_{}_change"
                  .format(post._meta.app_label, post._meta.model_name), 
                  args=[post.pk])

        context = {
            "site_title": post.title,
            "page_title": '<a href="{}">{}</a>'.format(post_edit_url, post.title),
            "post": post,
        }
        return render(request, "blog/detail.html", context)

    except Post.DoesNotExist:
        return render(None, "blog/404.html", context={})



def blog_search(request):
    query = request.GET.get("q")

    if query:
        # Basic search with postgres
        search_results = Post.objects.annotate(
            search=SearchVector("title", "body")
            ).filter(search=SearchQuery(query))

    else:
        search_results = Post.objects.none()

    # Output to Template
    context = {
        "site_title": 'Search: {}'.format(query),
        "page_title": 'search: {}'.format(query),
        "page_obj": paginate(search_results, request),
        "query": query,
    }
    return render(request, "blog/search_results.html", context)



def advanced_search(request):
    queryset = Post.objects.all()
    selected_categories = request.GET.getlist("categories")  # This is getlist instead of regular get!
    post_filter = PostFilter(request.GET, selected_categories=selected_categories, queryset=queryset)

    """
    THIS SECTION NEEDS CAREFUL ATTENTION!
    FIX THE FIELD NAMES AFTER MODIFYING FILTERS!

    This section makes the advanced search page show *NOTHING* instead
    of *EVERYTHING* if there are no filters applied.

    This combined with the qs override in the filter (filters.py) makes
    the advanced search page show no posts when first loading into the
    page and when there's an invalid filter applied.
    """
    s1 = request.GET.get("title__icontains")  # used for highlighting
    s2 = request.GET.get("body__icontains")  # used for highlighting
    s3 = request.GET.get("created_on__date")
    s4 = request.GET.get("created_on__date__gte")
    s5 = request.GET.get("created_on__date__lte")
    s6 = selected_categories  # being passed to PostFilter object for filtering
    s7 = request.GET.get("anniversary_date")

    # Omitting a check for the custom filters ("and_categories" and "sort_how").
    # If those are the only options selected, then return nothing.
    valid_requests = [s1, s2, s3, s4, s5, s6, s7]
    if any(valid_requests):
        search_results = post_filter.qs
    else:
        search_results = Post.objects.none()


    # Output to Template
    # Get category names from ID to make highlighting easier.
    query_categories = [Category.objects.get(id=category_id).name for category_id in s6]

    context = {
        "site_title": 'Advanced Search',
        "form": post_filter.form,
        "page_obj": paginate(search_results, request),
        "query_title": s1,  # for highlighting
        "query_body": s2,  # for highlighting
        "query_categories": query_categories,  # for highlighting
    }
    return render(request, "blog/advanced_search.html", context)



class ArchiveTimeView(TemplateView):
    """
    The master view that the daily, monthly, and yearly archives inherit from.
    """
    def get_prev_and_next(self, **kwargs):
        """
        prev_link, this_link, next_link are lists in the order of [year, month, day].
        Returns a list of [prev_link, this_link, next_link].
        """	
        this_link = list(kwargs.values())
        this_index = self.dates_list.index(this_link)

        # Previous (unit of time), skipping over empty (unit of time).
        prev_index = this_index - 1
        prev_link = self.dates_list[prev_index] if self.is_valid_index(prev_index) else None

        # Next (unit of time), skipping over empty (unit of time).
        next_index = this_index + 1
        next_link = self.dates_list[next_index] if self.is_valid_index(next_index) else None

        return [prev_link, this_link, next_link]

    def is_valid_index(self, index):
        return (0 <= index) and (index < len(self.dates_list))



class ArchiveDayView(ArchiveTimeView):
    template_name = "blog/archive_day.html"

    def get_context_data(self, **kwargs):
        year = self.kwargs["year"]
        month = self.kwargs["month"]
        day = self.kwargs["day"]
        day_date = date(year, month, day)

        search_results = Post.objects.filter(
            created_on__date = day_date
            ).order_by("-created_on")

        # Steps for nav links
        dates = Post.objects.dates("created_on", "day", "ASC")
        self.dates_list = [[date.year, date.month, date.day] for date in dates]
        nav_links = self.get_prev_and_next(**kwargs)

        # Output to Template
        day_date = day_date.strftime("%b %-d, %Y")

        context = {
            "site_title": day_date,
            "page_title": day_date,
            "page_obj": search_results,
            "prev_day": nav_links[0],
            "this_day": nav_links[1],
            "next_day": nav_links[2],
        }
        return context



class ArchiveMonthView(ArchiveTimeView):
    template_name = "blog/archive_month.html"

    def get_context_data(self, **kwargs):
        year = self.kwargs["year"]
        month = self.kwargs["month"]

        search_results = Post.objects.filter(
            created_on__year = year,
            created_on__month = month
            ).order_by("-created_on")

        # Steps for nav links
        dates = Post.objects.dates("created_on", "month", "ASC")
        self.dates_list = [[date.year, date.month] for date in dates]
        nav_links = self.get_prev_and_next(**kwargs)

        # Output to Template
        month_date = date(year, month, 1).strftime("%B %Y")

        context = {
            "site_title": month_date,
            "page_title": month_date,
            "page_obj": search_results,
            "prev_month": nav_links[0],
            "this_month": nav_links[1],
            "next_month": nav_links[2],
        }
        return context



class ArchiveYearView(ArchiveTimeView):
    template_name = "blog/archive_year.html"

    def get_context_data(self, **kwargs):
        year = self.kwargs["year"]

        posts_list = Post.objects.filter(
            created_on__year = year
            ).order_by("created_on")

        search_results = posts_list.annotate(month=TruncMonth("created_on"))
        cal = HTMLCalendar(year, posts_list).printyear()

        # Steps for nav links
        dates = Post.objects.dates("created_on", "year", "ASC")
        self.dates_list = [[date.year] for date in dates]
        nav_links = self.get_prev_and_next(**kwargs)

        # Output to Template
        context = {
            "site_title": 'Year {}'.format(year),
            "page_obj": search_results,
            "prev_year": nav_links[0],
            "this_year": nav_links[1],
            "next_year": nav_links[2],
            "cal": cal,
        }
        return context



class ArchiveView(TemplateView):
    template_name = "blog/archive.html"

    def get_context_data(self, **kwargs):
        dates = Post.objects.dates("created_on", "year", "DESC")
        years = [date.year for date in dates]

        # Output to Template
        context = {
            "site_title": 'Archives',
            "page_title": 'Archives',
            "years": years,
        }
        return context

blog/templates/blog/advanced_search.html
{% extends "blog/search_results.html" %}
{% load static %}


{% block page_title %}
    <h2 id="advanced_search_title">Advanced Search &#8648;</h2>
{% endblock page_title %}


{% block page_content %}
    <!-- Display search form first. -->
    <div id="advanced_search_form_container">
        <form action="{% url "advanced_search" %}" id="advanced_search_form" method="GET">
            {% for field in form %}
                <div class="field_wrapper">
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            
            <div class="advanced_search_buttons">
                <input type="reset" value="Reset">
                <input type="button" value="Clear Categories" id="clear_multi_choices">
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>


    <!-- Then print search results. -->
    {% if page_obj %}
        {% for post in page_obj %}
            <div class="blog_post">
                {% comment %}
                This is for cleaning up the invisible highlight that shows up in the source code.
                {% endcomment %}
                <!-- Post Title-->
                {% if query_title %}
                    <h3><a href="{% url "blog_detail" post.pk %}">
                        {{ post.title | highlighter:query_title }}
                    </a></h3>
                {% else %}
                    <h3><a href="{% url "blog_detail" post.pk %}">
                        {{ post.title }}
                    </a></h3>
                {% endif %}
                
                <!-- Date and Categories -->
                <div class="post_meta_info">
                    <small>
                        {{ post.created_on.date | date:"M j, Y" }} | Categories:
                        {% for category in post.categories.all %}
                            {% comment %}
                            The following line is all on a single line because spaces and line breaks add an extra space at the end of each category tag, which does not look as good if the list is stylized to add commas in between each item.
                            It also checks to if any of the categories were searched, and if so, highlights it. Otherwise, it outputs the category without the template filter that would cause invisible highlights that shows up in the source code.
                            {% endcomment %}
                            <a href="{% url "blog_category" category.name %}">{% if category.name in query_categories %}{{ category.name | highlighter:category.name }}{% else %}{{ category.name }}{% endif %}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </small>
                </div>

                {% comment %}
                Even though autoescape was off, the post body was still being escaped if searching in any field except the body.
                {% endcomment %}
                <!-- Post Body -->
                <div class="post_body">
                    {% if query_body %}
                        <p>{{ post.formatted_markdown | highlighter:query_body | safe }}</p>
                    {% else %}
                        <p>{{ post.formatted_markdown | safe }}</p>
                    {% endif %}
                </div>

            </div>
        {% endfor %}

    {% else %}
        <p>No posts found.</p>

    {% endif %}

    <script src="{% static "blog/js/advanced_search.js" %}"></script>
{% endblock page_content %}

blog/templates/blog/archive.html
{% extends "blog/base.html" %}


{% block page_content %}
    <ul>
    {% for year in years %}
        <li><a href="{% url "archive_year" year %}">{{ year }}</a></li>
    {% endfor %}
    </ul>
{% endblock page_content %}

blog/templates/blog/archive_day.html
{% extends "blog/index.html" %}


{% block page_navigation %}
    {% if next_day %}
    <a href="{% url "archive_day" next_day.0 next_day.1 next_day.2 %}">
        {{ next_day.1 | month_name }} {{ next_day.2 }}, {{ next_day.0 }}
    </a>
    {% endif %}

    <span class="current_page">
        ~{{ this_day.1 | month_name }} {{ this_day.2 }}, {{ this_day.0 }}~
    </span>

    {% if prev_day %}
    <a href="{% url "archive_day" prev_day.0 prev_day.1 prev_day.2 %}">
        {{ prev_day.1 | month_name }} {{ prev_day.2 }}, {{ prev_day.0 }}
    </a>
    {% endif %}

{% endblock page_navigation %}

blog/templates/blog/archive_month.html
{% extends "blog/base.html" %}


{% block page_content %}
    {% if page_obj %}
        <div class="monthly_post_list">
            <!-- List of Posts -->
            <ul class="archive_index">
                {% for post in page_obj %}
                    <li>
                        <span class="archive_index_date">{{ post.created_on.date | date:"M j, Y" }}</span> - 
                        <a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>

        </div>

    {% else %}
        <p>No posts found.</p>

    {% endif %}
{% endblock page_content %}


{% block page_navigation %}
    {% if next_month %}
        <a href="{% url "archive_month" next_month.0 next_month.1 %}">
            {{ next_month.1 | month_name }} {{ next_month.0 }}
        </a>
    {% endif %}

    <span class="current_page">
        ~{{ this_month.1 | month_name }} {{ this_month.0 }}~
    </span>

    {% if prev_month %}
        <a href="{% url "archive_month" prev_month.0 prev_month.1 %}">
            {{ prev_month.1 | month_name }} {{ prev_month.0 }}
        </a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/archive_year.html
{% extends "blog/base.html" %}


{% block page_content %}
    {% if page_obj %}
        <!-- Prints the calendar first. -->
         <div class="calendar_container">
            {{ cal | safe }}
         </div>

        <!-- Then prints the post list. -->
        {% regroup page_obj by month as post_months %}
        <!-- Regroup produces a list of group objects. -->
        <!-- Each group object has two attributes: grouper and list. -->

        {% for monthly in post_months %}
            <div class="monthly_post_list">
                <!-- Month Header Link -->
                <h3><a href="{% url "archive_month" monthly.grouper|date:"Y" monthly.grouper|date:"m" %}">
                    {{ monthly.grouper | date:"F" }}
                </a></h3>

                <!-- List of Posts -->
                <ul class="archive_index">
                    {% for post in monthly.list %}
                        <li>
                            <span class="archive_index_date">{{ post.created_on.date | date:"M j, Y" }}</span> - 
                            <a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        {% endfor %}

    {% else %}
        <p>No posts found.</p>

    {% endif %}
{% endblock page_content %}


{% block page_navigation %}
    {% if next_year %}
        <a href="{% url "archive_year" next_year.0 %}">
            {{ next_year.0 }}
        </a>
    {% endif %}

    <span class="current_page">
        ~{{ this_year.0 }}~
    </span>

    {% if prev_year %}
        <a href="{% url "archive_year" prev_year.0 %}">
            {{ prev_year.0 }}
        </a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en" data-theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>My Personal Blog 
        {% block site_title %}
            {% if site_title %}
            | {{ site_title }}
            {% endif %}
        {% endblock site_title %}
    </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/sakura.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
    <script src="{% static "blog/js/jquery-3.7.1.min.js" %}"></script>

    {% block extrahead %}{% endblock extrahead %}
</head>


<body>
    <div class="website_title">
        <h1><a href="{% url "blog_index" %}">My Personal Blog</a></h1>
    </div>

    <div class="top_nav_bar">
        <div class="nav_links">
            <span id="color_mode_switcher">&#9775;</span> &#8226; 
            <a href="{% url "blog_archives" %}">Archives</a> &#8226; 
            <a href="{% url "advanced_search" %}">Search</a> 
        </div>

        <div class="search_form">
            <form method="GET" action="{% url 'blog_search' %}">
                <input type="text" name="q" placeholder="Search">
                <button type="submit">Search</button>
            </form>
        </div>
    </div>
    <hr>

    <div class="page_title">
        {% block page_title %}
            {% if page_title %}
                <h2>{{ page_title | safe }}</h2>
            {% endif %}
        {% endblock page_title %}
    </div>
    
    <div class="page_content">
        {% block page_content %}{% endblock page_content %}
    </div>

    <hr>
    <div class="pagination">
        {% block page_navigation %}
            <span class="current_page">~</span>
        {% endblock page_navigation %}
    </div>

    <script src="{% static "blog/js/color_mode.js" %}"></script>
    <script src="{% static "blog/js/remove_p.js" %}"></script>
</body>

</html>

blog/templates/blog/category.html
{% extends "blog/index.html" %}


{% block page_title %}
    {{ block.super }}
    {% if category.description %}
        <div class="category_description">{{ category.description }}</div>
    {% endif %}
{% endblock page_title %}

blog/templates/blog/category_definition.html
{% extends "blog/base.html" %}


{% block page_title %}
    {{ block.super }}
    {% if category.description %}
        <div class="category_description">{{ category.description }}</div>
    {% endif %}
    <br>
{% endblock page_title %}


{% block page_content %}
    {% if page_obj %}
        <ul class="category_posts_list">
            <!-- All the posts in this category. -->
            {% for post in page_obj %}
                <li>
                    <span class="archive_index_date">{{ post.created_on.date | date:"M j, Y" }}</span> - 
                    <a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a>
                </li>

                {% for connection in post.connection_set.select_related %}
                    {% if connection.category.name == category.name and connection.comment %}
                    <!-- If there's a comment on the connection. -->
                    <ul class="connection_comment">
                        <li>{{ connection.comment }}</li>
                    </ul>
                    {% endif %}
                {% endfor %}

            {% endfor %}
        </ul>
    {% else %}
        <p>No posts found.</p>

    {% endif %}
{% endblock page_content %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}


{% block page_title %}
    <h2 class="blog_detail_title">{{ page_title | safe }}</h2>
{% endblock page_title %}


{% block page_content %}
    <div class="blog_post">
        <!-- Date and Categories -->
        <div class="post_meta_info">
            <small>
                {{ post.created_on.date | date:"M j, Y" }} | Categories:
                {% for category in post.categories.all %}
                    <a href="{% url "blog_category" category.name %}">{{ category.name | safe }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </small>
        </div>

        <!-- Post Body -->
        <div class="post_body">
            <p>{{ post.formatted_markdown | safe }}</p>
        </div>

    </div>
{% endblock page_content %}


{% block page_navigation %}
    {% if post.get_next_by_created_on.pk %}
        <a href="{% url "blog_detail" post.get_next_by_created_on.pk %}">newer</a>
    {% endif %}

    <span class="current_page">~</span>

    {% if post.get_previous_by_created_on %}
        <a href="{% url "blog_detail" post.get_previous_by_created_on.pk %}">older</a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/detail_extended.html
{% extends "blog/base.html" %}


{% block page_title %}
    <h2 class="blog_detail_title">{{ page_title | safe }}</h2>
{% endblock page_title %}


{% block page_content %}
    <div class="blog_post">
        <!-- Post Metadata -->
        <div class="post_meta_info">
            <small>
                {{ post.created_on.date | date:"M j, Y" }} {% comment %}| Categories:
                {% for category in post.categories.all %}
                    <a href="{% url "blog_category" category.name %}">{{ category.name | safe }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
                {% endcomment %}
            </small>
        </div>

        <!-- Post Body -->
        <div class="post_body">
            <p>{{ post.formatted_markdown | safe }}</p>
        </div>
        
    </div>

    <!-- Section Explaining the Categories -->
    <div class="post_categories">
        <h3>Categories</h3>
        <ul class="categories_list">
            {% for connection in post.connection_set.select_related %}
                <li>
                    <a href="{% url "blog_category" connection.category.name %}">{{ connection.category.name }}</a> {% if connection.comment %}- {{ connection.comment }}{% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock page_content %}


{% block page_navigation %}
    {% if post.get_next_by_created_on.pk %}
        <a href="{% url "blog_detail" post.get_next_by_created_on.pk %}">newer</a>
    {% endif %}

    <span class="current_page">~</span>

    {% if post.get_previous_by_created_on %}
        <a href="{% url "blog_detail" post.get_previous_by_created_on.pk %}">older</a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/detail_test.html
{% extends "blog/base.html" %}


{% block page_content %}
    <div class="blog_post">
        <!-- Date and Categories -->
        <small>
            {{ post.created_on.date | date:"M j, Y" }} | Categories:
            {% for category in post.categories.all %}
                <a href="{% url "blog_category" category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </small>

        <!-- Post Body -->
        <p>{{ post.formatted_markdown }}</p>
    </div>
{% endblock page_content %}


{% block page_navigation %}
    {% if post.get_previous_by_created_on %}
        <a href="{% url "blog_detail" post.get_previous_by_created_on.pk %}">prev</a>
    {% endif %}

    <span class="current_page">~</span>

    {% if post.get_next_by_created_on.pk %}
        <a href="{% url "blog_detail" post.get_next_by_created_on.pk %}">next</a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}


{% block page_content %}
    {% if page_obj %}
        {% for post in page_obj %}
            <div class="blog_post">
                <!-- Post Title-->
                <h3><a href="{% url "blog_detail" post.pk %}">
                    {{ post.title }}
                </a></h3>

                <!-- Date and Categories -->
                <div class="post_meta_info">
                    <small>
                        {{ post.created_on.date | date:"M j, Y" }} | Categories:
                        {% for category in post.categories.all %}
                            {% comment %}
                            the following line is all on a single line because spaces and line breaks add an extra space at the end of each category tag, which does not look as good if the list is stylized to add commas in between each item.
                            {% endcomment %}
                            <a href="{% url "blog_category" category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </small>
                </div>

                <!-- Post Body -->
                <div class="post_body">
                    <p>{{ post.formatted_markdown | safe }}</p>
                </div>

            </div>
        {% endfor %}

    {% else %}
        <p>No posts found.</p>

    {% endif %}
{% endblock page_content %}


{% block page_navigation %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; newest</a>
        <a href="?page={{ page_obj.previous_page_number }}">newer</a>
    {% endif %}

    <span class="current_page">
        ~page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}~
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">older</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">oldest &raquo;</a>
    {% endif %}
{% endblock page_navigation %}

blog/templates/blog/search.html
{% extends "blog/index.html" %}

{% block page_navigation %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?q={{ request.GET.q }}&page=1">&laquo; first</a>
                <a href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">prev</a>
            {% endif %}

            <span class="current">
                ~page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}~
            </span>

            {% if page_obj.has_next %}
                <a href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">next</a>
                <a href="?q={{ request.GET.q }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock page_navigation %}

blog/templates/blog/search_results.html
{% extends "blog/base.html" %}


{% block page_content %}
    {% if page_obj %}
        {% for post in page_obj %}
            <div class="blog_post">
                <!-- Post Title-->
                <h3><a href="{% url "blog_detail" post.pk %}">
                    {{ post.title | highlighter:query }}
                </a></h3>

                <!-- Date and Categories -->
                <div class="post_meta_info">
                    <small>
                        {{ post.created_on.date | date:"M j, Y" }} | Categories:
                        {% for category in post.categories.all %}
                            {% comment %}
                            the following line is all on a single line because spaces and line breaks add an extra space at the end of each category tag, which does not look as good if the list is stylized to add commas in between each item.
                            {% endcomment %}
                            <a href="{% url "blog_category" category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </small>
                </div>

                <!-- Post Body -->
                <div class="post_body">
                    <p>{{ post.formatted_markdown | highlighter:query}}</p>
                </div>

            </div>
        {% endfor %}

    {% else %}
        <p>No posts found.</p>

    {% endif %}
{% endblock page_content %}


{% block page_navigation %}
    {% if page_obj.has_previous %}
        <a href="{% querystring page=1 %}">&laquo; first</a>
        <a href="{% querystring page=page_obj.previous_page_number %}">prev</a>
    {% endif %}

    <span class="current_page">
        ~page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}~
    </span>

    {% if page_obj.has_next %}
        <a href="{% querystring page=page_obj.next_page_number %}">next</a>
        <a href="{% querystring page=page_obj.paginator.num_pages %}">last &raquo;</a>
    {% endif %}
{% endblock page_navigation %}